base.url=https://aiacademy.conceptgood.com/

test.email=aishwaryatesting04@gmail.com

test.password=Password@1234

new.name=Shivaai

new.email=shivaaipaithani01@gmail.com

new.password=Testing@1234

module.navigation.delay=40000


